### ISSUE TITLE
关于半监督的工作

### ISSUE THREAD

**Issue by thb1314** [Kinpzz/RCRNet-Pytorch#1]
您好，读了您的文章后，我有一个这样一个问题：您用fgplg生成的 pseudo label和存在的gt 合在一起训练RCRNet 效果会比全部使用 GT效果要好么？因为我发现生成的 pseudo label对应的图片实际上是有GT的。

**Comment by Kinpzz** [comment]
@thb1314 

谢谢您的关注。首先，在我们的实验中，我们发现使用部分伪标签和GT进行训练会达到比全部GT更好的效果（参考Section 4.4）。这一点在标注质量比较低的数据集中尤为明显（如VOS)，在标注质量比较高的数据中（如DAVIS）较为不明显。所以我们认为生成的伪标签能在一定程度上提升连续帧标注的一致性，提升标注质量，进而带来模型训练效果的提升。

其次，我们在DAVIS、VOS、FBMS数据上使用了半监督学习的概念，即使用部分有GT的帧和使用部分无GT的帧，通过使用不同比例的GT和伪标签来验证使用我们生成的伪标签的有效性。最后，我们发现视频任务不需要特别密集的标注即可达到不错的效果（所以我们没有进一步给他们未提供标注的帧生成伪标签），只使用部分GT配合伪标签就可以达到超过使用全部GT的效果。目前这3个数据上所生成的伪标签都是有对应的GT存在的，但我们在外部比较中只使用了20%的GT，主要目的是用来验证半监督策略的有效性。但是，对于将来其他更大规模的视频数据集的构建，我们就可以考虑只标注部分关键帧，配合伪标签以减轻人工标注成本。

**Comment by thb1314** [comment]
好的，谢谢您的回答，我明白了
