### ISSUE TITLE
Imagesets txt

### ISSUE THREAD

**Issue by Roudgers** [Kinpzz/RCRNet-Pytorch#3]
Hello, may I ask you about how can I get the MSRA-B_id.txt？

**Comment by Kinpzz** [comment]
@Roudgers It is the image name (exclude the file postfix like .jpg) of the training set of MSRA-B.  You can find the dataset at https://mmcheng.net/msra10k/

**Comment by Roudgers** [comment]
Thanks for your reply. And that's very helpful for me.



---Original---
