### ISSUE TITLE
训练集

### ISSUE THREAD

**Issue by wangbo-zhao** [Kinpzz/RCRNet-Pytorch#4]
您好
看论文里，你们使用了DAVIS(3455)+VOS(7650)+FBMS(720)总共11825的GT数据，然后在此基础上，每5张图片使用1个GT同时生成1个pseudo label(论文中1/5setting)，也就是大概2365GT+2365pseudo label来训练模型。 而不是利用VOS和FBMS的稀疏标注，使用GT来给未标注的数据生成label。请问我这样理解对吗？
感谢您回复

**Comment by wangbo-zhao** [comment]
刚才描述有点问题，这个对标注敏感型的实验是在VOS上做的，因此就是7650的GT中 只用20%，而完全没有用到VOS中未标注的数据

**Comment by Kinpzz** [comment]
@wangbo-zhao 是的，进一步引入VOS的未标注数据不能带来明显提升，标注敏感实验分析都还是在VOS提供的GT基础上进行分析的，主要关注如何减少对GT的依赖。

**Comment by wangbo-zhao** [comment]
好的 谢谢
