### ISSUE TITLE
预训练模型数据集划分

### ISSUE THREAD

**Issue by MENGHAH** [Kinpzz/RCRNet-Pytorch#5]
前辈你好，请问对于图像预训练模型的两个数据集，是如何划分测试集、交叉验证集以及训练集的？

**Comment by Kinpzz** [comment]
使用的是作者划分好的数据集，可以参考
MSRA-B: https://mmcheng.net/msra10k/
HKU-IS: https://sites.google.com/site/ligb86/hkuis
