### ISSUE TITLE
伪标签生成器如何验证在测试集上的性能

### ISSUE THREAD

**Issue by Lanezzz** [Kinpzz/RCRNet-Pytorch#6]
前辈您好，最近一直在看您的RCRNet，有两个不太理解的地方。第一是，您的伪标签生成器输入是7个通道，其中有相邻帧的真值，但是在测试集上跑的时候，我们不可能把测试集的真值输入到伪标签生成器啊？那么论文中的伪标签生成器在VOS的test数据集的性能是如何得到的呢（Table 4 ）？ 第二，为什么伪标签能起到作用呢？它相比于真值，感觉还是不够好。。我是否可以这样理解：伪标签的指导意义远比它的错误信息多，所以能对训练结果有帮助？

**Comment by Kinpzz** [comment]
@Lanezzz 感谢关注

1. 首先伪标签生成器仅应用于训练阶段，在仅有少量标签的情况（半监督设定）下去训练伪标签生成器，以及使用训练好的伪标签生成器为有少量关键标注的【训练集】进行伪标签的生成（或者称补全）。然后，利用补全的伪标签及带有标注的关键帧训练RCRNet+NER（视频分割模型），最终训练好的视频模型才会再VOS测试集上进行测试（注意训练好的视频模型不同于伪标签生成器，无需7个通道输入）。
2. 第二个问题文章中也有进行了分析，对于视频显著性分割任务而言，并非越多真值就更好，因为部分人工标注存在着歧义性，可能会导致模型退化。所以文章实验分析发现，在仅有部分真值标签的情况下（例如20%左右），通过伪标签生成的方式，可以补全时序信息，修正标签的前后一致性，最终甚至可以超越全部使用真值训练的模型性能。但是当真值标签过少时，是无法达到超越全部使用真值标签的性能的，但是伪标签也可以通过补全时序信息，在一定程度上提升模型性能

**Comment by Lanezzz** [comment]
@Kinpzz 感谢前辈回复地那么快，我针对第一个问题还是有点不太明白。您说的我是能理解的，但是我看论文中有这张表
![图片](https://user-images.githubusercontent.com/65452535/136644590-04f90804-de92-4000-b567-afa298fd2843.png)
即您做的关于增加输入信息的消融实验，这些数据是怎么获得的呢？文中只说了在20帧里面，用一帧真值和7帧伪标签。另外对应您补充材料里的数据
![图片](https://user-images.githubusercontent.com/65452535/136644666-6f6d31cf-bcf0-4cc6-9e6c-05158b124a78.png)
见我绿色标注的地方，我发现这两个数据是能对应上的，因此我推断出Table4，即第一个表也是在VOS test数据集上的数据，因此我很好奇您是怎么做这个实验的，怎么在测试集上验证伪标签生成器的性能的？

**Comment by Kinpzz** [comment]
@Lanezzz **The effectiveness of FGPLG**:  “To validate the effectiveness and necessity of each component, we train three separate RCRNet+NER with pseudo labels generated by our proposed FGPLG including its two variants, each of which takes different channels as input.” 消融实验是用不同的标签比例、伪标签生成器组件去训练伪标签生成器，拿训练好的伪标签生成器来训练相同视频模型，最终以视频模型在测试集上的性能来间接衡量伪标签生成器的好坏。

**Comment by Lanezzz** [comment]
@Kinpzz 好的，前辈，我明白了。非常感谢您的回答。另外想请问下，您现在还关注VSOD这个领域吗，我现在是研二，正想做半监督的VSOD，如果您还关注的话，可以加个Q或者V吗，有啥想法还可以交流请教下，我的V是  l15151855126

-
